### ISSUE TITLE
Add zoom fix

### ISSUE THREAD

**Issue by NYehor** [NYehor/GraphAlgorithm#15]

**Comment by AkulovBogdan** [comment]
Maybe this is not an issue. I found out that I set a 6-line scroll on my computer. Need to check on the machines of other participants
![image](https://user-images.githubusercontent.com/31021059/81854380-b3feed80-9512-11ea-9f87-56145e571f80.png)

**Comment by NYehor** [comment]
It is not your own problem. I have been asked to fix this form from different users.
