### ISSUE TITLE
Rename 'За замовчуванням' button

### ISSUE THREAD

**Issue by AkulovBogdan** [NYehor/GraphAlgorithm#23]
![image](https://user-images.githubusercontent.com/31021059/81994045-dc164b80-95fb-11ea-9fb2-49164b2c83de.png)
The purpose of this button is to enable selection and moving

**Comment by NYehor** [comment]
Yeah. I have opinion to call this button like "Пересунути". And we need to block the movement of elements after deactivation this button.
